version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.4
jobs:
  build-app:
    docker:
      - image: circleci/python:2.7-node
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - aws-s3/sync:
          from: dist
          to: 's3://art-test-ci-alpha/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
          overwrite: true
workflows:
  perform_build:
    jobs:
      - build-app:
          filters:
            branches:
              only: master
